#	$NetBSD: Makefile,v 1.3 2010/05/24 20:31:17 pgoyette Exp $

.include <bsd.own.mk>

LIB=	png

SRCS=	png.c png.c       pngget.c  pngpread.c  pngrio.c    pngrutil.c  pngtest.c   pngwio.c    pngwtran.c
SRCS+=	pngerror.c  pngmem.c  pngread.c   pngrtran.c  pngset.c    pngtrans.c  pngwrite.c  pngwutil.c

INCSDIR= /usr/include
INCS=	png.h pngconf.h pnglibconf.h pngdebug.h pnginfo.h pngpriv.h pngstruct.h

.include <bsd.lib.mk>
